In [4]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
import pandas as pd
import numpy as np
from sklearn import preprocessing

In [5]:
df = pd.read_csv("../../pre_processing/datasets/backward_filtered_analysis.csv", sep = ",")

In [6]:
if "RA" in df.columns:
    print("Removing column RA")
    df.drop('RA', inplace=True, axis=1)

In [336]:
df.head()

EVADIDO  BOLSISTA  GRADE_CORRENTE  NOTA_MEDIA  TOT_MAT_CURSADAS  \
0        0         1            2019         7.0                10   
1        1         1            2016         5.5                18   
2        1         0            2014         3.0                12   
3        1         1            2014         5.1                49   
4        0         1            2019         5.4                10   

   TOT_APROVACOES  TOT_REPROVACOES  TOT_REPROV_FREQ  SIF001  SIF002   ...    \
0               9                1                0       1       1   ...     
1              15                3                3       1       1   ...     
2               6                6                0       1       1   ...     
3              37               12               10       1       1   ...     
4               8                2                2       1       1   ...     

   SIF042  SIF043  SIF047  SIF049  SIF058  SIF063  SIF064  SIF029  SIF006  \
0       0       0       0       0       0       1       1       4       0   
1       1       0       0       0       0       1       1       0       1   
2       0       0       0       0       0       0       4       0       4   
3       1       1       1       1       1       1       1       1       1   
4       0       0       0       0       0       0       1       0       0   

   SIF073  
0       1  
1       0  
2       0  
3       0  
4       1  

[5 rows x 25 columns]

In [337]:
X = df.iloc[:, df.columns != "EVADIDO"].values
y = df["EVADIDO"]

In [338]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [361]:
clf = DecisionTreeClassifier(criterion="gini", splitter="best", max_depth=10)

In [362]:
clf.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=10,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [363]:
predictions = clf.predict(X_test)

In [364]:
predictions

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0], dtype=int64)

In [365]:
np.asarray(y_test)

array([0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0], dtype=int64)

In [366]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [367]:
print(confusion_matrix(y_test, predictions))

[[84 17]
 [ 6 60]]


In [368]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.93      0.83      0.88       101
           1       0.78      0.91      0.84        66

   micro avg       0.86      0.86      0.86       167
   macro avg       0.86      0.87      0.86       167
weighted avg       0.87      0.86      0.86       167



In [369]:
print("Model accuracy: ", accuracy_score(y_test, predictions), "%")

Model accuracy:  0.8622754491017964 %


In [359]:
from sklearn import tree
import graphviz 

In [360]:
feature_names = df.drop("EVADIDO", axis = 1)
feature_names = feature_names.columns
class_names = ["EVADIDO","NÃO EVADIDO"]

dot_data = tree.export_graphviz(clf, out_file = None,
                    feature_names=feature_names,
                    class_names=class_names,
                    filled=True, 
                    rounded=True,
                    special_characters=True,
                    precision=3)

graph = graphviz.Source(dot_data)
graph.format = "png"
graph.render('dtree_render',view=True)

'dtree_render.png'