In [72]:
# imports
import numpy as np
import pandas as pd
import keras
from datetime import datetime
from keras.utils import to_categorical
from keras.layers import Dropout
from keras.utils.vis_utils import plot_model
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from keras.utils import to_categorical

In [73]:
df = pd.read_csv("../pre_processing/datasets/no_filtered_analysis.csv", sep=",")

In [3]:
df.head()

RA  EVADIDO  RESID_ARARAS  BOLSISTA  \
0  002edf3eae2ce5635d797b35345ffdea        0             1         1   
1  003719ff8ca88d5266775000fbd3c7f9        1             0         1   
2  01563df7114a12af3f8cbd0cb4082491        1             0         0   
3  016ed164e805bc35f38559a5de19f818        1             0         1   
4  017a04be49784c0140a9506efe4aea86        0             0         1   

   GRADE_CORRENTE  NOTA_MEDIA  PONTUACAO_PS  TOT_MAT_CURSADAS  TOT_APROVACOES  \
0            2019         7.0          47.0                10               9   
1            2016         5.5          47.0                18              15   
2            2014         3.0          46.0                12               6   
3            2014         5.1          47.0                49              37   
4            2019         5.4          30.0                10               8   

   TOT_REPROVACOES   ...    SIF029  SIF030  SIF038  SIF039  SIF070  NCS037  \
0                1   ...         4       0       0       0       0       0   
1                3   ...         0       0       0       0       0       0   
2                6   ...         0       0       0       0       0       0   
3               12   ...         1       1       5       4       1       1   
4                2   ...         0       0       0       0       0       0   

   NCS040  SIF006  SIF072  SIF073  
0       0       0       1       1  
1       0       1       0       0  
2       0       4       0       0  
3       1       1       0       0  
4       0       0       2       1  

[5 rows x 63 columns]

In [4]:
# Dropo a coluna de RA
df.drop("RA", axis=1, inplace=True)

In [5]:
X = df.iloc[:, df.columns != "EVADIDO"].values

In [6]:
y = df["EVADIDO"]

In [7]:
y = to_categorical(y)

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [9]:
scaler_object = MinMaxScaler()

In [10]:
# TODO: Converd years to timestamp to scale after
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [11]:
scaled_X_train = scaler_object.transform(X_train)

In [12]:
scaled_X_test = scaler_object.transform(X_test)

In [13]:
from keras.models import Sequential
from keras.layers import Dense

In [74]:
# Configurate neural network features (layers, layer density, etc)
model = Sequential()
model.add(Dense(units=8, input_dim=61, activation='relu'))
model.add(Dropout(rate = 0.1))
model.add(Dense(units=4, input_dim=61, activation='relu'))
model.add(Dense(units=2, activation='softmax'))

adam = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='categorical_crossentropy', optimizer = adam, metrics=['accuracy'])

In [75]:
# NN summary
model.summary()
#plot_model(model, to_file='model_plot.png', show_shapes=True, show_layer_names=True) not running on windows

Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_23 (Dense)             (None, 8)                 496       
_________________________________________________________________
dropout_1 (Dropout)          (None, 8)                 0         
_________________________________________________________________
dense_24 (Dense)             (None, 4)                 36        
_________________________________________________________________
dense_25 (Dense)             (None, 2)                 10        
Total params: 542
Trainable params: 542
Non-trainable params: 0
_________________________________________________________________


In [76]:
model.fit(scaled_X_train, y_train, epochs=150, verbose=2)

Epoch 1/150
 - 0s - loss: 0.6844 - accuracy: 0.5579
Epoch 2/150
 - 0s - loss: 0.6754 - accuracy: 0.6973
Epoch 3/150
 - 0s - loss: 0.6613 - accuracy: 0.7596
Epoch 4/150
 - 0s - loss: 0.6439 - accuracy: 0.8220
Epoch 5/150
 - 0s - loss: 0.6332 - accuracy: 0.7953
Epoch 6/150
 - 0s - loss: 0.6101 - accuracy: 0.7982
Epoch 7/150
 - 0s - loss: 0.6041 - accuracy: 0.7745
Epoch 8/150
 - 0s - loss: 0.5669 - accuracy: 0.8338
Epoch 9/150
 - 0s - loss: 0.5496 - accuracy: 0.8338
Epoch 10/150
 - 0s - loss: 0.5273 - accuracy: 0.8279
Epoch 11/150
 - 0s - loss: 0.4977 - accuracy: 0.8398
Epoch 12/150
 - 0s - loss: 0.4718 - accuracy: 0.8546
Epoch 13/150
 - 0s - loss: 0.4453 - accuracy: 0.8635
Epoch 14/150
 - 0s - loss: 0.4485 - accuracy: 0.8398
Epoch 15/150
 - 0s - loss: 0.4241 - accuracy: 0.8813
Epoch 16/150
 - 0s - loss: 0.4112 - accuracy: 0.8635
Epoch 17/150
 - 0s - loss: 0.3902 - accuracy: 0.8665
Epoch 18/150
 - 0s - loss: 0.3970 - accuracy: 0.8665
Epoch 19/150
 - 0s - loss: 0.3752 - accuracy: 0.8635
Ep

In [77]:
# Spits out probabilities by default.
model.predict_classes(scaled_X_test)

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0], dtype=int64)

In [78]:
model.evaluate(x=scaled_X_test, y=y_test)

167/167 [==============================] - 0s 389us/step


[0.26061168446869193, 0.946107804775238]

In [79]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [80]:
predictions = model.predict_classes(scaled_X_test)

In [81]:
predictions

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0], dtype=int64)

In [67]:
# If you use only predictions it will return scaled values between 0 and 1 due to MinMaxScaler... possible
# workaround below
y_test.argmax(axis=1)

array([0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0], dtype=int64)

In [68]:
print(confusion_matrix(y_test.argmax(axis=1), predictions))

[[93  8]
 [ 2 64]]


In [69]:
print(classification_report(y_test.argmax(axis=1), predictions))

              precision    recall  f1-score   support

           0       0.98      0.92      0.95       101
           1       0.89      0.97      0.93        66

   micro avg       0.94      0.94      0.94       167
   macro avg       0.93      0.95      0.94       167
weighted avg       0.94      0.94      0.94       167



In [70]:
print("Model accuracy: ", accuracy_score(y_test.argmax(axis=1), predictions), "%")

Model accuracy:  0.9401197604790419 %


In [27]:
# Save the Neural Network model architecture
now = datetime.now()
current_time = now.strftime("%d%m%Y_%H%M%S")

# Create logic to create folder structure if it doesn't exist!
model.save(f"train_{current_time}_model.h5")

In [28]:
# TODO (URGENTE!!)
# Verificar os scripts de pre-processamento e ajustar a seleção de features para não remover
# a coluna evadido... (Apenas forward apresentou o problema)