In [9]:
# imports
import numpy as np
import pandas as pd
from datetime import datetime
from keras.utils import to_categorical
from keras.utils.vis_utils import plot_model
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from keras.utils import to_categorical

In [10]:
df = pd.read_csv("../pre_processing/datasets/boruta_filtered.csv", sep=",")

In [11]:
df.head()

EVADIDO  RESID_ARARAS  BOLSISTA  GRADE_CORRENTE  NOTA_MEDIA  PONTUACAO_PS  \
0        0             1         1            2019         7.0          47.0   
1        1             0         1            2016         5.5          47.0   
2        1             0         0            2014         3.0          46.0   
3        1             0         1            2014         5.1          47.0   
4        0             0         1            2019         5.4          30.0   

   TOT_MAT_CURSADAS  TOT_APROVACOES  TOT_REPROVACOES  TOT_REPROV_FREQ   ...    \
0                10               9                1                0   ...     
1                18              15                3                3   ...     
2                12               6                6                0   ...     
3                49              37               12               10   ...     
4                10               8                2                2   ...     

   SIF029  SIF030  SIF038  SIF039  SIF070  NCS037  NCS040  SIF006  SIF072  \
0       4       0       0       0       0       0       0       0       1   
1       0       0       0       0       0       0       0       1       0   
2       0       0       0       0       0       0       0       4       0   
3       1       1       5       4       1       1       1       1       0   
4       0       0       0       0       0       0       0       0       2   

   SIF073  
0       1  
1       0  
2       0  
3       0  
4       1  

[5 rows x 62 columns]

In [12]:
# Dropo a coluna de RA
df.drop("RA", axis=1, inplace=True)

KeyError: "['RA'] not found in axis"

In [13]:
X = df.iloc[:, df.columns != "EVADIDO"].values

In [14]:
y = df["EVADIDO"]

In [15]:
y = to_categorical(y)

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [17]:
scaler_object = MinMaxScaler()

In [18]:
# TODO: Converd years to timestamp to scale after
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [19]:
scaled_X_train = scaler_object.transform(X_train)

In [20]:
scaled_X_test = scaler_object.transform(X_test)

In [21]:
from keras.models import Sequential
from keras.layers import Dense

In [22]:
# Configurate neural network features (layers, layer density, etc)
model = Sequential()
model.add(Dense(units=8, input_dim=61, activation='relu'))
model.add(Dense(units=8, input_dim=61, activation='relu'))
model.add(Dense(units=2, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer = 'adam', metrics=['accuracy'])

Instructions for updating:
Colocations handled automatically by placer.


In [23]:
# NN summary
model.summary()
#plot_model(model, to_file='model_plot.png', show_shapes=True, show_layer_names=True) not running on windows

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 8)                 496       
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 18        
Total params: 586
Trainable params: 586
Non-trainable params: 0
_________________________________________________________________


In [27]:
model.fit(scaled_X_train, y_train, epochs=150, verbose=2)

Epoch 1/150
 - 0s - loss: 0.0298 - accuracy: 0.9911
Epoch 2/150
 - 0s - loss: 0.0293 - accuracy: 0.9911
Epoch 3/150
 - 0s - loss: 0.0300 - accuracy: 0.9911
Epoch 4/150
 - 0s - loss: 0.0291 - accuracy: 0.9911
Epoch 5/150
 - 0s - loss: 0.0291 - accuracy: 0.9911
Epoch 6/150
 - 0s - loss: 0.0298 - accuracy: 0.9881
Epoch 7/150
 - 0s - loss: 0.0313 - accuracy: 0.9911
Epoch 8/150
 - 0s - loss: 0.0289 - accuracy: 0.9911
Epoch 9/150
 - 0s - loss: 0.0299 - accuracy: 0.9911
Epoch 10/150
 - 0s - loss: 0.0281 - accuracy: 0.9911
Epoch 11/150
 - 0s - loss: 0.0294 - accuracy: 0.9881
Epoch 12/150
 - 0s - loss: 0.0288 - accuracy: 0.9911
Epoch 13/150
 - 0s - loss: 0.0278 - accuracy: 0.9911
Epoch 14/150
 - 0s - loss: 0.0285 - accuracy: 0.9911
Epoch 15/150
 - 0s - loss: 0.0278 - accuracy: 0.9911
Epoch 16/150
 - 0s - loss: 0.0279 - accuracy: 0.9911
Epoch 17/150
 - 0s - loss: 0.0290 - accuracy: 0.9911
Epoch 18/150
 - 0s - loss: 0.0295 - accuracy: 0.9911
Epoch 19/150
 - 0s - loss: 0.0285 - accuracy: 0.9911
Ep

In [26]:
# Spits out probabilities by default.
model.predict_classes(scaled_X_test)

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0], dtype=int64)

In [27]:
model.evaluate(x=scaled_X_test, y=y_test)

167/167 [==============================] - 0s 228us/step


[0.3244533430851862, 0.940119743347168]

In [28]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [29]:
predictions = model.predict_classes(scaled_X_test)

In [30]:
predictions

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0], dtype=int64)

In [31]:
# If you use only predictions it will return scaled values between 0 and 1 due to MinMaxScaler... possible
# workaround below
y_test.argmax(axis=1)

array([0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0], dtype=int64)

In [32]:
print(confusion_matrix(y_test.argmax(axis=1), predictions))

[[94  7]
 [ 3 63]]


In [33]:
print(classification_report(y_test.argmax(axis=1), predictions))

              precision    recall  f1-score   support

           0       0.97      0.93      0.95       101
           1       0.90      0.95      0.93        66

   micro avg       0.94      0.94      0.94       167
   macro avg       0.93      0.94      0.94       167
weighted avg       0.94      0.94      0.94       167



In [34]:
print("Model accuracy: ", accuracy_score(y_test.argmax(axis=1), predictions), "%")

Model accuracy:  0.9401197604790419 %


In [35]:
# Save the Neural Network model architecture
now = datetime.now()
current_time = now.strftime("%d%m%Y_%H%M%S")

# Create logic to create folder structure if it doesn't exist!
model.save(f"train_{current_time}_model.h5")

In [28]:
# TODO (URGENTE!!)
# Verificar os scripts de pre-processamento e ajustar a seleção de features para não remover
# a coluna evadido... (Apenas forward apresentou o problema)

Predicted=[9.9987769e-01 1.2227971e-04]
Predicted=[4.501619e-10 1.000000e+00]
Predicted=[5.5623588e-08 1.0000000e+00]
Predicted=[3.202797e-11 1.000000e+00]
Predicted=[9.9999499e-01 4.9989585e-06]
Predicted=[9.9999881e-01 1.2237747e-06]
Predicted=[9.9999619e-01 3.8236535e-06]
Predicted=[9.9999559e-01 4.4407107e-06]
Predicted=[2.4998812e-25 1.0000000e+00]
Predicted=[9.9999893e-01 1.0305984e-06]
Predicted=[7.735660e-08 9.999999e-01]
Predicted=[9.9954516e-01 4.5478254e-04]
Predicted=[3.455241e-09 1.000000e+00]
Predicted=[0.99796546 0.00203456]
Predicted=[1.167531e-09 1.000000e+00]
Predicted=[0.00369074 0.9963092 ]
Predicted=[0.00147551 0.9985245 ]
Predicted=[8.757894e-09 1.000000e+00]
Predicted=[0.2558279  0.74417204]
Predicted=[1.0005087e-09 1.0000000e+00]
Predicted=[9.9997580e-01 2.4162608e-05]
Predicted=[9.9999762e-01 2.4419892e-06]
Predicted=[9.9973768e-01 2.6233436e-04]
Predicted=[1.1642808e-07 9.9999988e-01]
Predicted=[9.9999154e-01 8.4859057e-06]
Predicted=[0.98405564 0.01594438]
Pr

IndexError: index 167 is out of bounds for axis 0 with size 167